swagger: '2.0'
info:
  title: JTHub Job Execution Service API
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
security:
  # enable OAuth protection for all REST endpoints
  # (only active if the TOKENINFO_URL environment variable is set)
  - oauth2: [uid]
paths:
  /job_queues/{account_name}:
    get:
      tags: [Job Queues]
      operationId: app.get_job_queues1
      summary: Get all job queues under a given account
      parameters:
        - $ref: '#/parameters/account_name'
      responses:
        200:
          description: Return job queues for the specified account
          schema:
            type: array
  /job_queues/{account_name}/{workflow_name}/{workflow_version}:
    get:
      tags: [Job Queues]
      operationId: app.get_job_queues2
      summary: Get all job queues for given account, workflow_name and version
      parameters:
        - $ref: '#/parameters/account_name'
        - $ref: '#/parameters/workflow_name'
        - $ref: '#/parameters/workflow_version'
      responses:
        200:
          description: Return job queues for the specified account
          schema:
            type: array
    post:
      tags: [Job Queues]
      operationId: app.register_job_queue1
      summary: Register a job queue under a given account, workflow_name and version
      parameters:
        - $ref: '#/parameters/account_name'
        - $ref: '#/parameters/workflow_name'
        - $ref: '#/parameters/workflow_version'
        - name: job_queue
          in: body
          schema:
            $ref: '#/definitions/JobQueue'
      responses:
        200:
          description: Workflow created
          schema:
            $ref: '#/definitions/JobQueue'
        409:
          description: Workflow registration failed
  /job_queues/{account_name}/{workflow_owner}/{workflow_name}/{workflow_version}:
    get:
      tags: [Job Queues]
      operationId: app.get_job_queues
      summary: Get all job queues for given account, workflow_owner, workflow_name and version
      parameters:
        - $ref: '#/parameters/account_name'
        - $ref: '#/parameters/workflow_owner'
        - $ref: '#/parameters/workflow_name'
        - $ref: '#/parameters/workflow_version'
      responses:
        200:
          description: Return job queues for the specified account
          schema:
            type: array
    post:
      tags: [Job Queues]
      operationId: app.register_job_queue
      summary: Register a job queue under a given account, workflow_owner, workflow_name and version
      parameters:
        - $ref: '#/parameters/account_name'
        - $ref: '#/parameters/workflow_owner'
        - $ref: '#/parameters/workflow_name'
        - $ref: '#/parameters/workflow_version'
        - name: job_queue
          in: body
          schema:
            $ref: '#/definitions/JobQueue'
      responses:
        200:
          description: Job queue registered
          schema:
            $ref: '#/definitions/JobQueue'
        409:
          description: Workflow registration failed
  /job_queues/{account_name}/{job_queue_id}/action:
    put:
      tags: [Job Queues]
      operationId: app.job_queue_action
      summary: Perform an action on a job queue, eg, pause, resume
      parameters:
        - $ref: '#/parameters/account_name'
        - $ref: '#/parameters/job_queue_id'
        - name: action
          in: body
          required: true
          schema:
            $ref: '#/definitions/JobQueueAction'
      responses:
        204:
          description: Action performed
  /jobs/{account_name}/{job_queue_id}:
    get:
      tags: [Jobs]
      operationId: app.get_jobs
      summary: Get jobs in a job queue
      parameters:
        - $ref: '#/parameters/account_name'
        - $ref: '#/parameters/job_queue_id'
        - name: state
          type: string
          in: query
          enum: ['queued', 'running', 'completed', 'failed', 'paused']
      responses:
        200:
          description: Return jobs
    post:
      tags: [Jobs]
      operationId: app.enqueue_job
      summary: Enqueue a job in a given job queue
      parameters:
        - $ref: '#/parameters/account_name'
        - $ref: '#/parameters/job_queue_id'
        - name: job_file
          in: body
          schema:
            $ref: '#/definitions/JobFile'
      responses:
        200:
          description: Job enqueued
          schema:
            $ref: '#/definitions/JobFile'
        409:
          description: Job enqueueing failed
  /jobs/{account_name}/{job_queue_id}/summary:
    get:
      tags: [Jobs]
      operationId: app.get_job_summary
      summary: Get summary information on jobs in a job queue
      parameters:
        - $ref: '#/parameters/account_name'
        - $ref: '#/parameters/job_queue_id'
        - name: state
          type: string
          in: query
          enum: ['queued', 'running', 'completed', 'failed', 'paused']
      responses:
        200:
          description: Return jobs
  /jobs/{account_name}/{job_queue_id}/{job_id}:
    get:
      tags: [Jobs]
      operationId: app.get_job
      summary: Get detail for a given job
      parameters:
        - $ref: '#/parameters/account_name'
        - $ref: '#/parameters/job_queue_id'
        - name: job_id
          in: path
          type: string
          required: true
          pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
      responses:
        200:
          description: Return job
  /jobs/{account_name}/{job_queue_id}/{job_id}/action:
    put:
      tags: [Jobs]
      operationId: app.job_action
      summary: Perform an action on a job, eg, pause, resume, cancel ...
      parameters:
        - $ref: '#/parameters/account_name'
        - $ref: '#/parameters/job_queue_id'
        - $ref: '#/parameters/job_id'
        - name: action
          in: body
          required: true
          schema:
            $ref: '#/definitions/JobAction'
      responses:
        204:
          description: Action performed
  /workers/{account_name}/{job_queue_id}:
    get:
      tags: [Workers]
      operationId: app.get_workers
      summary: Get workers registered for a job queue
      parameters:
        - $ref: '#/parameters/account_name'
        - $ref: '#/parameters/job_queue_id'
      responses:
        200:
          description: Return workers
    post:
      tags: [Workers]
      operationId: app.register_worker
      summary: Register a worker for a job queue
      parameters:
        - $ref: '#/parameters/account_name'
        - $ref: '#/parameters/job_queue_id'
        - name: worker
          in: body
          schema:
            $ref: '#/definitions/Worker'
      responses:
        200:
          description: Worker registered
  /workers/{account_name}/{job_queue_id}/{worker_id}:
    get:
      tags: [Workers]
      operationId: app.get_worker
      summary: Get detail of a given worker registered for a job queue
      parameters:
        - $ref: '#/parameters/account_name'
        - $ref: '#/parameters/job_queue_id'
        - $ref: '#/parameters/worker_id'
      responses:
        200:
          description: Return worker
          schema:
            $ref: '#/definitions/Worker'
  /workers/{account_name}/{job_queue_id}/{worker_id}/action:
    put:
      tags: [Workers]
      operationId: app.worker_action
      summary: Perform an action on a worker, eg, pause, resume
      parameters:
        - $ref: '#/parameters/account_name'
        - $ref: '#/parameters/job_queue_id'
        - $ref: '#/parameters/worker_id'
        - name: action
          in: body
          required: true
          schema:
            $ref: '#/definitions/WorkerAction'
      responses:
        204:
          description: Action performed
  /tasks/{account_name}/{job_queue_id}/{job_id}:
    get:
      tags: [Tasks]
      operationId: app.get_tasks
      summary: List all tasks for a given job
      parameters:
        - $ref: '#/parameters/account_name'
        - $ref: '#/parameters/job_queue_id'
        - $ref: '#/parameters/job_id'
      responses:
        200:
          description: Return tasks
  /tasks/{account_name}/{job_queue_id}/_next:
    post:
      tags: [Tasks]
      operationId: app.next_task
      summary: Worker asks for the next task to run
      parameters:
        - $ref: '#/parameters/account_name'
        - $ref: '#/parameters/job_queue_id'
        - name: worker
          in: body
          schema:
            $ref: '#/definitions/TaskFile'
      responses:
        204:
          description: Task assigned
        404:
          description: No task to run
  /tasks/{account_name}/{job_queue_id}/{job_id}/{task_name}/_complete:
    post:
      tags: [Tasks]
      operationId: app.complete_task
      summary: Worker reports completion of a task
      parameters:
        - $ref: '#/parameters/account_name'
        - $ref: '#/parameters/job_queue_id'
        - $ref: '#/parameters/job_id'
        - $ref: '#/parameters/task_name'
        - name: action
          in: body
          schema:
            $ref: '#/definitions/TaskAction'
      responses:
        204:
          description: Action performed
  /tasks/{account_name}/{job_queue_id}/{job_id}/{task_name}/_fail:
    post:
      tags: [Tasks]
      operationId: app.fail_task
      summary: Worker reports failure of a task
      parameters:
        - $ref: '#/parameters/account_name'
        - $ref: '#/parameters/job_queue_id'
        - $ref: '#/parameters/job_id'
        - $ref: '#/parameters/task_name'
        - name: action
          in: body
          schema:
            $ref: '#/definitions/TaskAction'
      responses:
        204:
          description: Action performed

parameters:
  account_name:
    name: account_name
    description: Account's unique name
    in: path
    type: string
    required: true
    pattern: "^[a-zA-Z0-9-_]{3,30}$"
  workflow_owner:
    name: workflow_owner
    description: Workflow owner's ccount name
    in: path
    type: string
    required: true
    pattern: "^[a-zA-Z0-9-_]{3,30}$"
  workflow_name:
    name: workflow_name
    description: Workflow's name
    in: path
    type: string
    required: true
    pattern: "^[a-zA-Z0-9-_]{3,30}$"
  workflow_version:
    name: workflow_version
    description: Workflow's version
    in: path
    type: string
    required: true
    pattern: "^[a-zA-Z0-9-_.]{3,30}$"
  job_id:
    name: job_id
    description: Unique ID for a job
    in: path
    type: string
    required: true
    pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
  job_queue_id:
    name: job_queue_id
    description: Unique ID for a job queue
    in: path
    type: string
    required: true
    pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
  worker_id:
    name: worker_id
    description: Unique ID for a worker
    in: path
    type: string
    required: true
    pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
  task_name:
    name: task_name
    description: Task's name
    in: path
    type: string
    required: true
    pattern: "^[a-zA-Z0-9-_.]{2,256}$"


definitions:
  JobQueue:
    type: object
    required:
      - name
    properties:
      id:
        type: string
        description: Workflow's unique identifier
        pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
        example: "7ebf7fa9-f70f-481a-a499-5fba3f8c5078"
        readOnly: true
      name:
        type: string
        description: Workflow's name
        pattern: "^[a-zA-Z0-9-_]{3,30}$"
        example: "BWA-MEM"
        minLength: 3
        maxLength: 30
      workflow_type:
        type: string
        description: In which language workflow is written
        enum: ["JTracker"]
        example: "JTracker"
        readOnly: true
      tags:
        type: object
        description: Custom tags
      created:
        type: string
        format: date-time
        description: Creation time
        example: "2015-07-07T15:49:51.230+02:00"
        readOnly: true
  JobFile:
    type: object
    required:
      - name
    properties:
      id:
        type: string
        description: Workflow's unique identifier
        pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
        example: "7ebf7fa9-f70f-481a-a499-5fba3f8c5078"
        readOnly: true
      name:
        type: string
        description: Workflow's name
        pattern: "^[a-zA-Z0-9-_]{3,35}$"
        example: "BWA-MEM"
        minLength: 3
        maxLength: 35
  TaskFile:
    type: object
    required:
      - name
    properties:
      id:
        type: string
        description: Workflow's unique identifier
        pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
        example: "7ebf7fa9-f70f-481a-a499-5fba3f8c5078"
        readOnly: true
      name:
        type: string
        description: Workflow's name
        pattern: "^[a-zA-Z0-9-_]{3,35}$"
        example: "BWA-MEM"
        minLength: 3
        maxLength: 35
  Worker:
    type: object
    required:
      - name
    properties:
      id:
        type: string
        description: Workflow's unique identifier
        pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
        example: "7ebf7fa9-f70f-481a-a499-5fba3f8c5078"
        readOnly: true
      name:
        type: string
        description: Workflow's name
        pattern: "^[a-zA-Z0-9-_]{3,35}$"
        example: "BWA-MEM"
        minLength: 3
        maxLength: 35
  JobQueueAction:
    type: object
    required:
      - name
    properties:
      id:
        type: string
        description: Workflow's unique identifier
        pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
        example: "7ebf7fa9-f70f-481a-a499-5fba3f8c5078"
        readOnly: true
      name:
        type: string
        description: Workflow's name
        pattern: "^[a-zA-Z0-9-_]{3,35}$"
        example: "BWA-MEM"
        minLength: 3
        maxLength: 35
  WorkerAction:
    type: object
    required:
      - name
    properties:
      id:
        type: string
        description: Workflow's unique identifier
        pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
        example: "7ebf7fa9-f70f-481a-a499-5fba3f8c5078"
        readOnly: true
      name:
        type: string
        description: Workflow's name
        pattern: "^[a-zA-Z0-9-_]{3,35}$"
        example: "BWA-MEM"
        minLength: 3
        maxLength: 35
  JobAction:
    type: object
    required:
      - name
    properties:
      id:
        type: string
        description: Workflow's unique identifier
        pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
        example: "7ebf7fa9-f70f-481a-a499-5fba3f8c5078"
        readOnly: true
      name:
        type: string
        description: Workflow's name
        pattern: "^[a-zA-Z0-9-_]{3,35}$"
        example: "BWA-MEM"
        minLength: 3
        maxLength: 35
  TaskAction:
    type: object
    required:
      - name
    properties:
      id:
        type: string
        description: Workflow's unique identifier
        pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
        example: "7ebf7fa9-f70f-481a-a499-5fba3f8c5078"
        readOnly: true
      name:
        type: string
        description: Workflow's name
        pattern: "^[a-zA-Z0-9-_]{3,35}$"
        example: "BWA-MEM"
        minLength: 3
        maxLength: 35

securityDefinitions:
  oauth2:
    type: oauth2
    flow: implicit
    authorizationUrl: https://example.com/oauth2/dialog
    scopes:
      uid: Unique identifier of the user accessing the service.
